In [13]:
import json
import numpy as np

x = '{"train":[[2,0,0,0],[3,1,0,0],[0,0,2,1],[0,1,3,1]],"test":[[1,0,0],[0,1,2]]}'
x = x.strip()
data = json.loads(x)

train = np.array(data['train'], dtype=np.int32)
test = np.array(data['test'], dtype=np.int32)

X_train = train[:, :-1]
y_train = train[:, -1]

n0 = np.sum(y_train == 0)
N = len(y_train)
pi0 = n0 / N
pi1 = 1 - pi0

X_train[y_train == 0], X_train[y_train == 1]

(array([[2, 0, 0],
        [3, 1, 0]], dtype=int32),
 array([[0, 0, 2],
        [0, 1, 3]], dtype=int32))

In [16]:
X_train[y_train == 0].sum(axis=0)

array([5, 1, 0])

In [22]:
count_0 = X_train[y_train == 0].sum(axis=0)
count_1 = X_train[y_train == 1].sum(axis=0)

logprob_0 = np.log((count_0 + 1) / np.sum(count_0 + 1, axis=0))
logprob_1 = np.log((count_1 + 1) / np.sum(count_1 + 1, axis=0))

logprob_0, logprob_1

(array([-0.40546511, -1.5040774 , -2.19722458]),
 array([-2.19722458, -1.5040774 , -0.40546511]))

In [32]:
score_0 = test @ logprob_0 + np.log(pi0)
score_1 = test @ logprob_1 + np.log(pi1)
pred = (score_1 >= score_0).astype(int)
pred.tolist()

[0, 1]