In [ ]:
import numpy as np

gamma = 0.9
R = np.array([1., 1., 0., 0., 1., 4., 0., 0., 0., 2.], dtype=np.float32)
R

array([1., 1., 0., 0., 1., 4., 0., 0., 0., 2.], dtype=float32)

In [3]:
P = np.random.randn(10, 10)
P = np.abs(P)
P = P / P.sum(axis=1, keepdims=True)
P

array([[0.08367576, 0.10222551, 0.00033713, 0.13180044, 0.05176766,
        0.03248962, 0.03286344, 0.21397321, 0.09760401, 0.25326323],
       [0.05189769, 0.02023128, 0.28701056, 0.17550244, 0.15881074,
        0.03949727, 0.11924505, 0.00439567, 0.04774999, 0.09565931],
       [0.09467767, 0.12309571, 0.05755184, 0.1417207 , 0.00489266,
        0.13378457, 0.1210187 , 0.17345692, 0.07990399, 0.06989724],
       [0.05387644, 0.22208004, 0.17232132, 0.07830477, 0.03774879,
        0.06001568, 0.17065377, 0.00887686, 0.04071618, 0.15540615],
       [0.05911083, 0.10016057, 0.17147538, 0.02522595, 0.09599694,
        0.03478759, 0.05438933, 0.1905677 , 0.08969262, 0.17859311],
       [0.10281983, 0.06758555, 0.10198171, 0.19649906, 0.19742731,
        0.07136642, 0.10636804, 0.06856941, 0.08178997, 0.00559269],
       [0.04072442, 0.05379895, 0.10504524, 0.17486347, 0.07405368,
        0.19525673, 0.06616071, 0.04751738, 0.13063871, 0.11194072],
       [0.14913241, 0.19187202, 0.0783804

In [4]:
I = np.eye(N=10)
V = np.linalg.inv(I - gamma * P) @ R
np.set_printoptions(suppress=True)
V.round(2)

array([ 9.4 ,  9.09,  8.37,  8.32,  9.27, 12.14,  8.62,  8.5 ,  8.84,
       10.57])